name: freckles
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - tqdm
  - click
  - matplotlib
  - healpy
  - astropy
  - emcee
  - numba
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - numdifftools
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark 
